### ISSUE TITLE
Convert issue

### ISSUE THREAD

**Issue by Drchip61** [Zyun-Y/BiconNets#2]
Thanks for sharing your code!
When I tried to convert the salient mask to the connectivity mask(sal2conn), and then convert it back(bv_test), the result is different.
If there is some special operation between this process?

**Comment by Zyun-Y** [comment]
> Thanks for sharing your code! When I tried to convert the salient mask to the connectivity mask(sal2conn), and then convert it back(bv_test), the result is different. If there is some special operation between this process?

Hi,

It's a good question.

The sal2conn function is used to convert discrete masks into connectivity masks **before** training while bv_test is used to convert the continuous connectivity outputs into masks **during** training so you can view the bv_test as a smooth version of the inverse operation of sal2conn. Also, we emphasize the bv_test is not used to do the inverse transform from connectivity to saliency mask offline.

Technically, here are the differences:

1. bv_test takes the sigmoid of the input.
2. At the end of the bv_test, we take the average across all directions. This is the main reason why the generated mask is "smoothed". The reason we do the average is that, as we said in the paper, we encourage there to be more connections from different directions learned by the training. However, if you only take max across the channels (which we did in our another paper: Connectivity-based deep learning approach for segmentation of the epithelium in _in vivo_ human esophageal OCT images), you will get the almost same as your original mask.


Hope this helps.
