### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by ZejunHe** [Zyun-Y/BiconNets#4]
what's the meaning of the translation matrix? and how to select the size in bicon_loss __init__ function?

**Comment by Zyun-Y** [comment]
Hi,

The translation matrices (i.e., hori_translation and verti_translation) were just used to translate the output map horizontally and vertically using a simple matrix multiplication. We were using these two translation matrices to generate the 8 shifted map that will be used for bilateral voting or any related operations.

The sizes of both, as described in the codes, are initialized with the shape of the output map (or any maps that you want to shift with).

Hope this helps.
________________________________
From: ZejunHe ***@***.***>
Sent: Monday, July 3, 2023 19:12
To: Zyun-Y/BiconNets ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Zyun-Y/BiconNets] some questions (Issue #4)


what's the meaning of the translation matrix? and how to select the size in bicon_loss init function?
